# Generated by Django 5.1.5 on 2025-02-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='valide',
            field=models.BooleanField(default=False),
        ),
    ]
