# Generated by Django 5.1.5 on 2025-02-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bonsortie_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='fichier_pdf',
            field=models.FileField(blank=True, help_text='Fichier PDF généré pour le rapport.', null=True, upload_to='rapports_pdfs/'),
        ),
    ]
