# Generated by Django 5.1.5 on 2025-02-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patient_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='docteur',
        ),
    ]
