# Generated by Django 5.1.5 on 2025-02-17 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_consultation_docteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_restante', models.PositiveIntegerField()),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='api.produitpharmaceutique')),
            ],
        ),
    ]
